version: 2.1

jobs:
  checkout_and_unit_test:
    machine: true
    steps:
      - run: echo "checking out and testing..."
  deploy_backend:
    machine: true
    steps:
      - run: echo "backend deploying..."
  integration_tests_backend:
    machine: true
    steps:
      - run: echo "testing the backend..."
  deploy_staging:
    machine: true
    steps:
      - run: echo "staging..."
  acceptance_tests_1:
    machine: true
    steps:
      - run: echo "first acceptance test..."
  acceptance_tests_2:
    machine: true
    steps:
      - run: echo "second acceptance test..."
  acceptance_tests_3:
    machine: true
    steps:
      - run: echo "third acceptance test..."
  acceptance_tests_4:
    machine: true
    steps:
      - run: echo "fourth acceptance test..."
  deploy_production:    
    machine: true
    steps:
      - run: echo "deploying the production..."
workflows:
  build:
    jobs:
      - checkout_and_unit_test
      - deploy_backend:
          requires:
            - checkout_and_unit_test
      - integration_tests_backend:
          requires:
            - deploy_backend
      - deploy_staging:
          requires:
            - integration_tests_backend
      - acceptance_tests_1:
          requires:
            - deploy_staging
      - acceptance_tests_2:
          requires:
            - deploy_staging
      - acceptance_tests_3:
          requires:
            - deploy_staging
      - acceptance_tests_4:
          requires:
            - deploy_staging
      - deploy_production:
          requires:
            - acceptance_tests_1
            - acceptance_tests_2
            - acceptance_tests_3
            - acceptance_tests_4
